name: Newsletter Finance

on: 
  workflow_dispatch:        # Permet de lancer manuellement aussi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run newsletter script
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          NEWSAPI_API_KEY: ${{ secrets.NEWSAPI_API_KEY }}
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
        run: |
          python newsletter.py

